server {
    listen 80;
    server_name localhost;
    root /var/www/html;
    index index.php index.html;
    client_max_body_size 64M;

    # REGLAS OFICIALES DE IMÁGENES PARA PRESTASHOP EN NGINX
    rewrite ^/c/([\w.-]+)/.+\.jpg$ /img/c/$1.jpg last;
    
    rewrite ^/(\d)(-[\w-]+)?/.+\.jpg$ /img/p/$1/$1$2.jpg last;
    rewrite ^/(\d)(\d)(-[\w-]+)?/.+\.jpg$ /img/p/$1/$2/$1$2$3.jpg last;
    rewrite ^/(\d)(\d)(\d)(-[\w-]+)?/.+\.jpg$ /img/p/$1/$2/$3/$1$2$3$4.jpg last;
    rewrite ^/(\d)(\d)(\d)(\d)(-[\w-]+)?/.+\.jpg$ /img/p/$1/$2/$3/$4/$1$2$3$4$5.jpg last;
    rewrite ^/(\d)(\d)(\d)(\d)(\d)(-[\w-]+)?/.+\.jpg$ /img/p/$1/$2/$3/$4/$5/$1$2$3$4$5$6.jpg last;
    rewrite ^/(\d)(\d)(\d)(\d)(\d)(\d)(-[\w-]+)?/.+\.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$1$2$3$4$5$6$7.jpg last;
    rewrite ^/(\d)(\d)(\d)(\d)(\d)(\d)(\d)(-[\w-]+)?/.+\.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$7/$1$2$3$4$5$6$7$8.jpg last;
    rewrite ^/(\d)(\d)(\d)(\d)(\d)(\d)(\d)(\d)(-[\w-]+)?/.+\.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9.jpg last;

    
    # Esta regla genérica va al final para que no pise a las anteriores
    rewrite ^/([0-9]+)\-([a-zA-Z0-9\-]*)(.*)$ /img/p/$1-$2$3 last;

    # 2. ENTRADA PRINCIPAL CORREGIDA PARA PRESTASHOP 9 (Symfony)
    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location /admin427swgumtqrpscy42yo {
        if (!-e $request_filename) {
            rewrite ^/.*$ /admin427swgumtqrpscy42yo/index.php last;
        }
    }

    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_pass ps9.1-gateway:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param PATH_TRANSLATED $document_root$fastcgi_path_info;
        fastcgi_read_timeout 300s;
        fastcgi_buffer_size          128k;
        fastcgi_buffers           4  256k;
        fastcgi_busy_buffers_size    256k;
    }

    location ~ /\. {
        deny all;
    }
}
